//
//  excuseNounBank.swift
//  Log-Line
//
//  Created by Petar Simonovic on 08/04/2021.
//

import Foundation

let excuseNounBank = ["your wedding",
                      "work",
                      "the deadline",
                      "your birthday",
                      "your dinner party",
                      "your play",
                      "school",
                      "your leaving party",
                      "your cake",
                      "your pizza",
                      "your cat",
                      "your dog",
                      "your vinyl",
                      "your speech",
                      "your joke",
                      "your graduation",
                      "your proposal",
                      "your business plan",
                      "your dreams",
                      "your song",
                      "your lyrics",
                      "your appraisal",
                      "our relationship",
                      "our future together",
                      "our house",
                      "your handwriting",
                      "your cooking",
                      "your hopes",
                      "your ambitions",
                      "your novel",
                      "your poem",
                      "our holiday",
                      "our anniversary",
                      "the reunion",
                      "your painting",
                      "your dancing",
                      "our day trip",
                      "lunch",
                      "breakfast",
                      "your IDM album",
                      "your rapping",
                      "your drum programming",
                      "our collaboration",
                      "the disciplinary hearing",
                      "the yoga class",
                      "the big game",
                      "ninja training",
                      "your feelings",
                      "your credibility",
                      "your problems",
                      "your mobile app",
                      "your story generator",
                      "your coding",
                      "your ghost story",
                      "your friends",
                      
                
];
