//
//  nounBank.swift
//  Log-Line
//
//  Created by Petar Simonovic on 05/04/2021.
//

import Foundation

let nounBank = ["computer",
                "watch maker",
                "ghost",
                "ninja",
                "pond",
                "frog",
                "dog",
                "robot",
                "android",
                "cat",
                "vampire",
                "houseplant",
                "chameleon",
                "penguin",
                "garden",
                "rubber duck",
                "alien",
                "turkey",
                "bartender",
                "lawyer",
                "criminal",
                "horse thief",
                "auditor",
                "beekeper",
                "hot dog",
                "astronaut",
                "scuba diver",
                "dancer",
                "coder",
                "liar",
                "CEO",
                "cook",
                "writer",
                "guitarist",
                "pedestrian",
                "IDM musician",
                "DJ",
                "wrestler",
                "rapper",
                "king",
                "queen",
                "prince",
                "princess",
                "monster",
                "superhero",
                "pilot",
                "singer",
                "planet",
                "book",
                "engineer",
                "werewolf",
                "witch",
                "wizard",
                "dragon",
                "goblin",
                "shark",
                "sloth",
                "detective",
                "zombie",
                "farmer",
                "editor",
                "writer",
                "brewer",
                "doctor",
                "nurse",
                "salad",
                "pizza",
                "tree",
                "author",
                "blogger",
                "book coach",
                "copy editor",
                "consultant",
                "dog writer",
                "freelancer",
                "ghostwriter",
                "griot",
                "hack writer",
                "infopreneur",
                "journalist",
                "medical writer",
                "novelist",
                "poet",
                "review",
                "screenwriter",
                "scribe",
                "script doctor",
                "scrivener",
                "songwriter",
                "speechwriter",
                "staff writer",
                "technical writer",
                "writer",
                "designer",
                "animator",
                "architect",
                "artisan",
                "art therapist",
                "baker",
                "ceramics artist",
                "colorist",
                "concept artist",
                "curator",
                "dancer",
                "essayist",
                "event planner",
                "fashion designer",
                "fine artist",
                "floral designer",
                "graphic designer",
                "hairstylist",
                "illustrator",
                "tattoo artist",
                "jeweller",
                "lyricist",
                "make-up artist",
                "marine designer",
                "media designer",
                "musician",
                "party planner",
                "penciller",
                "photographer",
                "photojournalist",
                "potter",
                "sculptor",
                "set decorator",
                "set dresser",
                "singer",
                "web designer",
                "wedding planner",
                "ballet historian",
                "ballet master",
                "choreographer",
                "dance critic",
                "dance historian",
                "dance notator",
                "dance scholar",
                "dance therapist",
                "dancer",
                "backup dancer",
                "exotic dancer",
                "showgirl",
                "taxi dancer",
                "acrobat",
                "athlete",
                "actor",
                "archimime",
                "barker",
                "beatboxer",
                "benshi",
                "bouffon",
                "circus performer",
                "clown",
                "comedian",
                "dancer",
                "drag queen",
                "drag king",
                "emcee",
                "filmmaker",
                "geisha",
                "harlequin",
                "host",
                "illusionist",
                "impressionist",
                "internet star",
                "itinerant poet",
                "kobzar",
                "lirnyk",
                "magician",
                "mime",
                "minstrel",
                "model",
                "monologist",
                "musician",
                "painter",
                "party princess",
                "performer",
                "photographer",
                "poet",
                "radio star",
                "rhapsode",
                "ring girl",
                "ringmaster",
                "scop",
                "shamakhi dancer",
                "showgirl",
                "showman",
                "showrunner",
                "singer",
                "skomorokh",
                "sport star",
                "street performer",
                "streamer",
                "stunt performer",
                "tiktoker",
                "tv celebrity",
                "vedette",
                "writer",
                "youtuber",
                "auto mechanic",
                "beader",
                "bobbin boy",
                "arborist",
                "feller",
                "foreman",
                "mechanic",
                "miller",
                "moldmaker",
                "panel beater",
                "patternmaker",
                "plant operator",
                "plumber",
                "welder",
                "sawfiler",
                "shop foreman",
                "soaper",
                "wheelwright",
                "woodworker",
                "construction worker",
                "factory worker",
                "biologist",
                "botanist",
                "demon",
                "god",
                "herpetologist",
                "microbiologist",
                "neuroscientist",
                "zoologist",
                "archaeologist",
                "astronaut",
                "astronomer",
                "biochemist",
                "chemist",
                "ecologist",
                "geographer",
                "naturalist",
                "oceanographer",
                "paleontologist",
                "pathologist",
                "anthropologist",
                "economist",
                "historian",
                "politician",
                "sociologist",
                "urban planner",
                "geographer",
                "geologist",
                "geoprofessions",
                "petroleum geologist",
                "chemist",
                "physicist",
                "crown",
                "rod",
                "sports car",
                "forest",
                "wood",
                "sprite",
                "beverage",
                "sword",
                "axe",
                "arrow",
                "road sign",
                "stone",
                "guitar",
                "drum",
                "drum machine",
                "TB 303",
                "watch",
                "clock",
                "flower",
                "house",
                "mansion",
                "mountain",
                "log cabin",
                "space station",
                "moon",
                "satellite",
                "hammer",
                "saw",
                "laptop",
                "hamburger",
                "eagle",
                "sparrow",
                "elf",
                "puffer fish",
                "discotheque",
                "ocean",
                "sea",
                "ship",
                "boat",
                "emu",
                "warehouse",
                "suburban estate",
                "music box",
                "terrarium"
                
                
                
]
