//
//  nounBank.swift
//  Log-Line
//
//  Created by Petar Simonovic on 05/04/2021.
//

import Foundation

let nounBank = ["computer",
                "broomstick",
                "warrant officer",
                "mammoth",
                "monolith",
                "cowboy",
                "potion",
                "victim",
                "arms dealer",
                "inventor",
                "wand",
                "boy",
                "gang of thugs",
                "girl",
                "storm",
                "priest",
                "protagonist",
                "professor",
                "holiday",
                "schoolteacher",
                "FBI agent",
                "police officer",
                "garment",
                "safe room",
                "daughter",
                "suit of armour",
                "son",
                "aunt",
                "uncle",
                "shelter",
                "nunchuck",
                "shuriken",
                "wind-up bird",
                "watch maker",
                "ghost",
                "poison",
                "ninja",
                "pond",
                "frog",
                "dog",
                "robot",
                "android",
                "usurper",
                "cat",
                "outsider",
                "vampire",
                "houseplant",
                "plague",
                "necromancer",
                "chameleon",
                "penguin",
                "garden",
                "gentleman",
                "ring",
                "count",
                "rubber duck",
                "alien",
                "family",
                "gladiator",
                "general",
                "emperor",
                "turkey",
                "bartender",
                "lawyer",
                "battle",
                "criminal",
                "horse thief",
                "auditor",
                "spy",
                "beekeper",
                "hot dog",
                "astronaut",
                "scuba diver",
                "dancer",
                "coder",
                "liar",
                "CEO",
                "cook",
                "writer",
                "guitarist",
                "pedestrian",
                "IDM musician",
                "businessman",
                "salaryman",
                "banker",
                "analyst",
                "proofreader",
                "copywriter",
                "waitress",
                "veteran",
                "DJ",
                "DEA agent",
                "narc",
                "auditor",
                "soldier",
                "future soldier",
                "wrestler",
                "rapper",
                "turkey baster",
                "king",
                "kingdom",
                "queen",
                "prince",
                "princess",
                "bag of cash",
                "resistance leader",
                "bomb",
                "timebomb",
                "environmentalist",
                "monster",
                "superhero",
                "pilot",
                "traffikcer",
                "police unit",
                "singer",
                "planet",
                "world war",
                "book",
                "engineer",
                "werewolf",
                "witch",
                "wizard",
                "dragon",
                "goblin",
                "shark",
                "sloth",
                "lord",
                "detective",
                "zombie",
                "farmer",
                "editor",
                "writer",
                "brewer",
                "doctor",
                "nurse",
                "salad",
                "pizza",
                "tree",
                "author",
                "blogger",
                "book coach",
                "copy editor",
                "consultant",
                "dog writer",
                "former priest",
                "freelancer",
                "ghostwriter",
                "occurence",
                "miracle cure",
                "crowd of tourists",
                "figure",
                "marketer",
                "griot",
                "hack writer",
                "infopreneur",
                "journalist",
                "inspector",
                "shopkeeper",
                "postman",
                "medical writer",
                "novelist",
                "poet",
                "review",
                "screenwriter",
                "scribe",
                "script doctor",
                "scrivener",
                "songwriter",
                "speechwriter",
                "staff writer",
                "technical writer",
                "writer",
                "designer",
                "animator",
                "architect",
                "artisan",
                "art therapist",
                "baker",
                "ceramics artist",
                "colorist",
                "concept artist",
                "curator",
                "dancer",
                "essayist",
                "event planner",
                "fashion designer",
                "fine artist",
                "floral designer",
                "graphic designer",
                "hairstylist",
                "illustrator",
                "tattoo artist",
                "jeweller",
                "lyricist",
                "make-up artist",
                "marine designer",
                "media designer",
                "musician",
                "phobia",
                "party planner",
                "penciller",
                "photographer",
                "photojournalist",
                "potter",
                "sculptor",
                "set decorator",
                "set dresser",
                "singer",
                "web designer",
                "wedding planner",
                "ballet historian",
                "ballet master",
                "choreographer",
                "dance critic",
                "dance historian",
                "dance notator",
                "dance scholar",
                "dance therapist",
                "dancer",
                "backup dancer",
                "taxi dancer",
                "acrobat",
                "athlete",
                "actor",
                "archimime",
                "barker",
                "beatboxer",
                "benshi",
                "bouffon",
                "beautiful",
                "circus performer",
                "nobleman",
                "clown",
                "comedian",
                "dancer",
                "emcee",
                "filmmaker",
                "geisha",
                "harlequin",
                "host",
                "illusionist",
                "impressionist",
                "internet star",
                "itinerant poet",
                "kobzar",
                "lirnyk",
                "magician",
                "mime",
                "minstrel",
                "model",
                "monologist",
                "musician",
                "painter",
                "party princess",
                "performer",
                "photographer",
                "poet",
                "radio star",
                "rhapsode",
                "ringmaster",
                "scop",
                "shamakhi dancer",
                "showman",
                "showrunner",
                "singer",
                "skomorokh",
                "sport star",
                "street performer",
                "streamer",
                "stunt performer",
                "tiktoker",
                "tv celebrity",
                "vedette",
                "writer",
                "youtuber",
                "auto mechanic",
                "beader",
                "bobbin boy",
                "arborist",
                "feller",
                "foreman",
                "mechanic",
                "miller",
                "moldmaker",
                "panel beater",
                "patternmaker",
                "plant operator",
                "plumber",
                "welder",
                "sawfiler",
                "shop foreman",
                "soaper",
                "wheelwright",
                "woodworker",
                "construction worker",
                "factory worker",
                "biologist",
                "botanist",
                "demon",
                "god",
                "herpetologist",
                "microbiologist",
                "neuroscientist",
                "zoologist",
                "archaeologist",
                "astronaut",
                "astronomer",
                "biochemist",
                "chemist",
                "ecologist",
                "geographer",
                "naturalist",
                "nation",
                "rebellion",
                "oceanographer",
                "paleontologist",
                "pathologist",
                "anthropologist",
                "economist",
                "historian",
                "politician",
                "sociologist",
                "urban planner",
                "geographer",
                "geologist",
                "geoprofessions",
                "petroleum geologist",
                "chemist",
                "physicist",
                "crown",
                "rod",
                "sports car",
                "forest",
                "wood",
                "sprite",
                "beverage",
                "sword",
                "axe",
                "arrow",
                "road sign",
                "stone",
                "guitar",
                "drum",
                "drum machine",
                "TB 303",
                "watch",
                "clock",
                "flower",
                "house",
                "mansion",
                "mountain",
                "log cabin",
                "space station",
                "moon",
                "satellite",
                "hammer",
                "saw",
                "laptop",
                "city",
                "hamburger",
                "eagle",
                "sparrow",
                "elf",
                "fish",
                "night",
                "day",
                "puffer fish",
                "discotheque",
                "ocean",
                "sea",
                "ship",
                "trader",
                "translator",
                "chateau",
                "career",
                "boat",
                "emu",
                "town",
                "hacker",
                "revoultion",
                "marine squadron",
                "sub-editor",
                "warehouse",
                "suburban estate",
                "music box",
                "terrarium",
                "swimming pool",
                "reindeer",
                "snowman",
                "framework",
                "resort",
                "apartment",
                "castle",
                "army",
                "force",
                "jet",
                "geyser",
                "earthquake",
                "volcano",
                "spreadsheet",
                "typewriter",
                "seance",
                "ouija board",
                "poltergeist",
                "roundabout",
                "potion",
                "drug",
                "pavement",
                "egg",
                "rock band",
                "metal band",
                "pop band",
                "stone circle",
                "concert",
                "party",
                "club",
                "record label",
                "novel",
                "poem",
                "song"
                
                
]
