//
//  storyBank.swift
//  Log-Line
//
//  Created by Petar Simonovic on 10/04/2021.
//

import Foundation
import SwiftUI

let storyBank =  [
    Story(title: "Dracula", logline: "A wise but bumbling professor must destroy an undead count before a virtuous  schoolteacher becomes a vampire", writer: "Bram Stoker", year: "1897", fact: "The working title of the novel was The Dead Undead", symbol: "\u{f043}"),
    Story(title: "The Lord Of The Rings", logline: "A brave but timid gentleman must destroy a magic ring before an evil necromancer takes over a world", writer: "JRR Tolien", year: "1954", fact: "Tolkien wrote his stories to provide a world for the Elvish languages he created",  symbol: "\u{f70b}"),
    Story(title: "Toy Story", logline: "A loyal but stubborn cowboy must rescue a brave astronaut before an upset boy leaves a home", writer: "Joss Whedon, Andrew Stanton, Joel Cohen, Alec Sokolow, John Lasseter, Andrew Stanton, Pete Docter, Joe Ranft", year: "1996", fact: "In early drafts, Woody was a ventriloquist’s dummy", symbol: "\u{f8c0}"),
    Story(title: "Alien", logline: "A tough but mistrustful warrant officer must escape an exploding spaceship before a ferocious alien eats a cat", writer: "Dan O'Bannon, Ronald Shusett", year: "1979", fact: "The original title was Star Beast", symbol: "\u{e001}"),
    Story(title: "Gladiator", logline: "An honourable but brooding general must avenge a murdered family before a vain emperor wins a contest", writer: "David Franzoni, John Loganm, William Nicholson", year: "2000", fact: "Only 21 pages of the script were written when shooting began", symbol: "\u{f6eb}"),
    Story(title: "Star Wars", logline: "A courageous but naive farmer must trust a mysterious force before a sinister lord destroys a rebellion", writer: "George Lucas", year: "1977", fact: "George Lucas based the struture of the narrative on Joseph Campbell’s monomyth theories in The Hero with a Thousand Faces", symbol: "\u{e033}"),
    Story(title: "The Godfather", logline: "A tactical but ruthless son must take over a clandestine dynasty before a rival family wins a war", writer: "Mario Puzo", year: "1969", fact: "In the Godfather films, oranges are used symbolically to foreshadow mortal danger or death", symbol: "\u{f441}"),
    Story(title: "Jaws", logline: "A dedicated but insecure outsider must overcome a severe phobia before a massive fish devours a town", writer: "Peter Benchley", year: "1974", fact: "Benchley and editor Thomas Congdon brainstormed more than 120 ideas for a title, including The Stillness in the Water and Leviathan Rising, before they decided on Jaws - 20 minutes before the book went to print.",  symbol: "\u{f21a}"),
    Story(title: "The Matrix", logline: "A powerful but doubtful hacker must comprehend an incredible truth before a ruthless computer crushes a revolution", writer: "Lana Wachowski, Lilly Wachowski", year: "1999", fact: "Jean Baudrillard's Simulacra and Simulation was required reading for the cast of the film, who had to be able to understand and explain The Matrix", symbol: "\u{f188}"),
    Story(title: "Halloween", logline: "A kind but terrified babysitter must survive a harrowing night before an insane serial killer murders a suburban estate", writer: "John Carpenter, Debra Hill", year: "1978", fact: "The screenplay, originally titled The Babysitter Murders, was written in less than two weeks",  symbol: "\u{f30e}"),
    Story(title: "Die Hard", logline: "A formidable but reckless policeman must rescue a kidnapped wife before an unpredictable terrorist ruins Christmas", writer: "Jeb Stuart, Steven E de Souza", year: "1988", fact: "The original script took place over three days but director John McTiernan — inspired by Shakespeare's 'A Midsummer Night's Dream' — decided the events should happen in a single night", symbol: "\u{f1ad}"),
    Story(title: "Ghostbusters", logline: "A capable but feckless team must eradicate a supernatural plague before a malignant god destroys a city", writer: "Dan Aykroyd, Harold Ramis", year: "1984", fact: "Ackroyd was inspired by an article from the American Society of Psychical Research and his family history: his great-grandfather, Samuel A Aykroyd, was a 19th century psychic investigator", symbol: "\u{f6e2}"),
    Story(title: "Back To The Future", logline: "An easy going but tardy teenager must rekindle a vital relationship before a new past replaces a future", writer: "Robert Zemeckis, Bob Gale", year: "1985", fact: "'The script was rejected over 40 times by every major studio and by some more than once', Bob Gale said. One studio suggested that the title should be changed to Space Man From Pluto",  symbol: "\u{f8ba}"),
    Story(title: "Hamlet", logline: "A thoughtful but melancholy prince must avenge a noble king before a manipulative usurper dispenses a poison", writer: "William Shakespeare", year: "c1600", fact: "In the first quarto, the play's most famous line is rendered as 'To be or not to be, I there’s the point'", symbol: "\u{f54c}"),
    Story(title: "The Simpsons Movie", logline: "A lazy but caring oaf must diffuse a suspended bomb before a power mad environmentalist destroys a dome", writer: "James L Brooks, Matt Groening, Al Jean, Ian Maxtone-Graham, George Meyer, David Mirkin, Mike Reiss, Mike Scully, Matt Selman, John Swartzwelder, Jon Vitti", year: "2007", fact: "The script was rewritten 153 times by a team of 11 writers", symbol: "\u{f706}"),
    Story(title: "Reservoir Dogs", logline: "A professional but hunted gang must uncover a traitorous informant before  an armed police unit storms a warehouse", writer: "Quentin Tarantino", year: "1992", fact: "The inspiration for the title has variously been ascribed to a mnishearing of Au Revoir les Enfants, French gangster slang for rat and a production company's label for its slush pile of unsolicited screenplays.", symbol: "\u{f508}"),
    Story(title: "The Nightmare Before Christmas", logline: "A well-meaning but terrifying skeleton must rekindle a spooky passion before a gambling boogeyman kills Santa.", writer: "Tim Burton, Michael McDowell", year: "1993", fact: "Burton was inspired to write the original poem after he saw a store replacing its Halloween display with Christmas products", symbol: "\u{f786}"),
    Story(title: "Bill & Ted\u{2019}s Excellent Adventure", logline: "A humurous but moronic rock band must complete an outstanding odyssey before a strict father exiles a son", writer: "Chris Matheson, Ed Solomon", year: "1989", fact: "The script was written by hand in four days", symbol: "\u{f8be}"),
    Story(title: "Signs", logline: "A family oriented but faithless former priest must investigate a strange occurrence before a nefarious alien civilisation invades a farm", writer: "M Night Shyamalan", year: "2002", fact: "The film was originally to be set entirely on the farm with no incidental music", symbol: "\u{f864}"),
    Story(title: "Take Shelter", logline: "A dedicated but troubled father must build a safe shelter before a supernatural storm obliterates a town", writer: "Jeff Nichols", year: "2011", fact: "For her role in the film, Jessica Chastain was paid just $100 a day", symbol: "\u{f76c}"),
    Story(title: "Panic Room", logline: "A wealthy but helpless divorcee must protect a diabetic daughter before a dangerous gang of thugs breaks into a safe room", writer: "David Koepp", year: "2002", fact: "David Koepp wrote his first draft in six days", symbol: "\u{f52b}"),
         Story(title: "The Silence Of The Lambs", logline: "A capable but inexperienced FBI agent must stop a serial killer before a kidnapped daughter becomes a garment", writer: "Ted Tally", year: "1991", fact: "In preparation for the role of Hannibal Lecter, Sir Anthony Hopkins visited murderers in prison and sat in court listening to gruesome cases", symbol: "\u{f711}"),
         Story(title: "Iron Man", logline: "A brilliant but arrogant inventor must create a powerful suit of armour before a megalomaniacal arms dealer takes over a company", writer: "Mark Fergus, Hawk Ostby, Art Marcum, Matt Holloway", year: "2008", fact: "The screenplay was not finished when filming began, so much of the dialogue was adlibbed", symbol: "\u{f5e7}"),
         Story(title: "Tenet", logline: "An expert but unaware protagonist must recover a mysterious device before a vengeful billionaire destroys the world", writer: "Christopher Nolan", year: "2020", fact: "Sir Kenneth Branagh had to learn to speak backwards in a Russian accent", symbol: "\u{f1da}"),
         Story(title: "Indiana Jones and the Kingdom of the Crystal Skull", logline: "A daring but ophidiophobic archaeologist must discover a lost kingdom before an annoying Shia LaBeouf swings with a monkey", writer: "George Lucas, Jeff Nathanson, David Koepp", year: "2008", fact: "Harrison Ford had kept himself in such good shape over the years, his costume measurements were exactly the same as for The Last Crusade", symbol: "\u{f6fb}"),
         Story(title: "The Last Of Us", logline: "A tough but emotionally closed-off trafficker must protect a vivacious girl before a vicious infected horde wipes out humanity’s last hope", writer: "Neil Druckmann, Bruce Straley", year: "2013", fact: "Druckmann first had the idea for the game while at university, when he dreamed-up a cross between Fumito Ueda’s ‘Ico’ and ‘Night of the Living Dead’", symbol: "\u{f11b}"),
         Story(title: "Frozen", logline: "A beautiful but cursed princess must control an amazing power before a treacherous nobleman steals a kingdom", writer: "Jennifer Lee, Chris Buck, Shane Morris", year: "2013", fact: "Hans, Kristoff, Anna and Sven are all references to Hans Christian Andersen", symbol: "\u{f7ad}"),
         Story(title: "The Terminator", logline: "A strong-willed but unsuspecting waitress must team with a future soldier before an unstoppable machine terminates a resistance leader", writer: "James Cameron", year: "1984", fact: "Schwarzenegger only has 14 lines in the entire film", symbol: "\u{e045}"),
         Story(title: "Don't Breathe", logline: "A devoted but naïve thief must find a bulging bag of cash before a blind veteran wields a turkey baster", writer: "Fede Alvarez, Rodo Sayagues", year: "2016", fact: "The street where the blind man lives is called ‘Buena Vista’, ironically the Spanish for ‘good view’", symbol: "\u{f29d}"),
        Story(title: "Total Recall", logline: "A devoted but haunted construction worker must visit a colonised Mars before a nefarious businessman reimplants memories", writer: "Ronald Shusett, Dan O’Bannon, Jon Povill, Gary Goldman", year: "1990", fact: "Schwarzenegger was so impressed with Sharon Stone’s preparation for her role, he referred to her as the ‘female terminator’", symbol: "\u{f4fb}"),
         Story(title: "Aliens", logline: "A capable but haunted warrant officer must take charge of a well-trained marine squadron before an infestation of chest-bursting aliens kill everyone", writer: "James Cameron", year: "1986", fact: "Bill Paxton improvised the line, ‘Game over man, game over!’", symbol: "\u{e020}"),
         Story(title: "A Good Year", logline: "A clever but unscrupulous trader must renovate a majestic chateau before an ill-tempered superior takes away a career", writer: "Marc Klein", year: "2006", fact: "All the scenes in France were shot within eight minutes’ drive of Ridley Scott’s own house", symbol: "\u{f72f}"),
         Story(title: "Arrival", logline: "A gifted but haunted translator must communicate with a benevolent alien before an unsettled nation begins a war", writer: "Erik Heisserer", year: "2016", fact: "When Erik Heisserer began developing the script, he created a mood board featuring his dream cast, which had Amy Adams in the lead", symbol: "\u{f67b}"),
         Story(title: "The Last Samurai", logline: "A celebrated but alcoholic soldier must join forces with Japanese warriors before an invading force attacks an indigenous people", writer: "John Logan, Edward Zwick, Marshall Herskovitz", year: "2003", fact: "Tom Cruise spent two years in preparation for the movie, learning swordplay and Japanese", symbol: "\u{f6a1}"),
         Story (title: "Sicario", logline: "A diligent but ill-informed DEA agent must assist a mysterious government agency before a violent cartel starts a war", writer: "Taylor Sheridan", year: "2015", fact: "While writing the screenplay, Taylor Sheridan’s wife bought a new car without telling him and threw the keys on his writing desk asking him how the script was coming along making him write faster", symbol: "\u{e051}"),
         Story(title: "District 9", logline: "A capable but bigoted inspector must find a miracle cure before an insidious infection creates an alien", writer: "Neill Blomkamp, Terri Tatchell", year: "2009", fact: "The sounds of the alien language were created by rubbing a pumpkin", symbol: "\u{e04a}"),
         Story(title: "Edge Of Tomorrow", logline: "An accomplished but sleazy marketer must repeat an intense battle before an invading alien force wipes out humanity", writer: "Christopher McQuarrie, Jez Butterworth, Jon-Henry Butterworth", year: "2014", fact: "The film started shooting while the script was still undergoing multiple revisions", symbol: "\u{f8f6}"),
         Story(title: "The Thinker", logline: "An iconic but crouching figure must ponder a glorious life before a Parisian crowd takes a photograph", writer: "Auguste Rodin", year: "1902", fact: "The statue was originally named ‘The Poet’", symbol: "\u{f808}")

]

